services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-dock
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      retries: 4
    networks:
      - my-network

  config-service:
    build: ./config-service
    container_name: config-dock
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=true    # S'enregistrer auprès d'Eureka
      - EUREKA_CLIENT_FETCH-REGISTRY=true
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      retries: 3
    networks:
      - my-network

  gateway-service:
    build: ./gateway-service
    container_name: gateway-dock
    ports:
      - '8085:8085'
    expose:
      - '8085'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:8888
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=true    # S'enregistrer auprès d'Eureka
      - EUREKA_CLIENT_FETCH-REGISTRY=true
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8085/actuator/health"]
      interval: 10s
      retries: 3
    networks:
      - my-network

  nurse-service:
    build: ./nurse-service
    container_name: nurse-dock
    ports:
      - '8082:8082'
    expose:
      - '8082'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:8888
      - CONFIG_SERVICE_URL=http://config-dock:8888
      - SPRING_APPLICATION_NAME=nurse-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/gestion_utilisateurs
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=asmae.br1762002
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=true    # S'enregistrer auprès d'Eureka
      - EUREKA_CLIENT_FETCH-REGISTRY=true
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 10s
      retries: 3
    networks:
      - my-network

  patient-service:
    build: ./patient-service
    container_name: patient-dock
    ports:
      - '8081:8081'
    expose:
      - '8081'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:8888
      - SPRING_APPLICATION_NAME=patient-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/gestion_utilisateurs
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=asmae.br1762002
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=true    # S'enregistrer auprès d'Eureka
      - EUREKA_CLIENT_FETCH-REGISTRY=true
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 10s
      retries: 3
    networks:
      - my-network

  appointment-service:
    build: ./appointment-service
    container_name: appointment-dock
    ports:
      - '8083:8083'
    expose:
      - '8083'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:8888
      - SPRING_APPLICATION_NAME=appointment-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/gestion_utilisateurs
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=asmae.br1762002
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=true    # S'enregistrer auprès d'Eureka
      - EUREKA_CLIENT_FETCH-REGISTRY=true
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 10s
      retries: 3
    networks:
      - my-network

  notification-service:
    build: ./notification-service
    container_name: notification-dock
    ports:
      - '8084:8084'
    expose:
      - '8084'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:8888
      - SPRING_APPLICATION_NAME=notification-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/gestion_utilisateurs
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=asmae.br1762002
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=true    # S'enregistrer auprès d'Eureka
      - EUREKA_CLIENT_FETCH-REGISTRY=true
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8084/actuator/health"]
      interval: 10s
      retries: 3
    networks:
      - my-network
  user-service:
    build: ./user-service
    container_name: user-dock
    ports:
      - '8080:8080'
    expose:
      - '8080'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-dock:8761/eureka
      - CONFIG_SERVICE_URL=http://config-dock:8888
      - SPRING_APPLICATION_NAME=user-service
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-db:3306/gestion_utilisateurs
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=asmae.br1762002
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
      - EUREKA_CLIENT_REGISTER-WITH-EUREKA=true    # S'enregistrer auprès d'Eureka
      - EUREKA_CLIENT_FETCH-REGISTRY=true
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
      mysql-db:
        condition: service_started
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      retries: 3
    networks:
      - my-network

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: asmae.br1762002
      MYSQL_DATABASE: gestion_utilisateurs
    ports: [ "3306:3306" ]
    networks: [ "my-network" ]
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 10s
      retries: 10

networks:  # <-- Déclaration du réseau
  my-network:
    driver: bridge
