name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: List directories
        run: ls -la

      - name: Build each microservice
        run: |
          for dir in */; do
            if [ -f "$dir/pom.xml" ]; then
              echo "Building $dir"
              mvn -f "$dir/pom.xml" clean install
            else
              echo "No pom.xml found in $dir, skipping..."
            fi
          done
